name: L1 Unit Tests for rdkNativeScript

permissions:
  contents: read
  checks: write

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  AUTOMATICS_UNAME: ${{ secrets.AUTOMATICS_UNAME }}
  AUTOMATICS_PASSCODE: ${{ secrets.AUTOMATICS_PASSCODE }}

jobs:
  build-externals:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git cmake gperf ruby-dev libglew-dev libglut-dev \
            libglib2.0-dev g++ meson bison libjpeg-dev libpng-dev \
            libfreetype6-dev libicu-dev autoconf libtool libxml2-dev \
            libcurl4-openssl-dev libexpat1-dev doxygen vim libcjson-dev \
            libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
            libwayland-bin libwayland-dev wayland-protocols \
            libreadline-dev net-tools

      - name: Export secrets to environment
        run: |
          echo "AUTOMATICS_UNAME=${AUTOMATICS_UNAME}" >> $GITHUB_ENV
          echo "AUTOMATICS_PASSCODE=${AUTOMATICS_PASSCODE}" >> $GITHUB_ENV

      - name: Make build.sh executable
        run: |
          chmod +x externals/build.sh
          find externals -type f -name "preparedashpc.sh" -exec chmod +x {} \;
          find externals -type f -name "copydashheaders.sh" -exec chmod +x {} \;    

      - name: Run build.sh
        run: |
          cd externals
          ./build.sh
